### ISSUE TITLE
Compile Issues - due to Kotlin update?

### ISSUE THREAD

**Issue by jkblgithub** [Daio-io/LifecycleDemoApp#1]
Hi 

This does not want to compile with the latest Kotlin - in AppLifecycleHandler.kt , "lifeCycleDelegate" cannot be resolved and in App.kt, the AppLifecycleHandler cannot be init with "this" as it gives a type mismatch. Sorry, today is the first time I have worked with Kotlin so not sure how to resolve. Could you help please?

**Comment by Daio-io** [comment]
Hi there,

Just tried with the latest version of Kotlin and having no issues. Did you manage to resolve this after? Let me know. If not can you post the error on here and I can have a look further for you :)

**Comment by Daio-io** [comment]
Closing because all seems fine :)
